services:
    mysql:
        container_name: mysql_eyepal
        restart: unless-stopped
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: asd123**!RacK
            MYSQL_DATABASE: eyepal
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
